export const NAV_BY_DEFAULT_BROWSER = 'NAV_BY_DEFAULT_BROWSER'
export const SELECT_DIR = 'SELECT_DIR'
export const GET_LIVE_URLS = 'GET_LIVE_URLS'
export const START_STREAM_RECORD = 'START_STREAM_RECORD'
export const STOP_STREAM_RECORD = 'STOP_STREAM_RECORD'
export const STREAM_RECORD_END = 'STREAM_RECORD_END'

export const FFMPEG_PROGRESS_INFO = 'FFMPEG_PROGRESS_INFO'
export const DOWNLOAD_DEP_PROGRESS_INFO = 'DOWNLOAD_DEP_PROGRESS_INFO'

export const SHOW_NOTIFICATION = 'SHOW_NOTIFICATION'
export const OPEN_LOGS_DIR = 'OPEN_LOGS_DIR'
export const SHOW_UPDATE_DIALOG = 'SHOW_UPDATE_DIALOG'

export const MINIMIZE_WINDOW = 'MINIMIZE_WINDOW'
export const MAXIMIZE_RESTORE_WINDOW = 'MAXIMIZE_RESTORE_WINDOW'
export const CLOSE_WINDOW = 'CLOSE_WINDOW'

export const RETRY_DOWNLOAD_DEP = 'RETRY_DOWNLOAD_DEP'

export const USER_CLOSE_WINDOW = 'USER_CLOSE_WINDOW'
export const FORCE_CLOSE_WINDOW = 'FORCE_CLOSE_WINDOW'

export const RECORD_DUMMY_PROCESS = { kill: () => {} }

export const RECORD_END_NOT_USER_STOP = 'RECORD_END_NOT_USER_STOP'
