export const NAV_BY_DEFAULT_BROWSER = 'NAV_BY_DEFAULT_BROWSER'
export const SELECT_DIR = 'SELECT_DIR'
export const GET_LIVE_URLS = 'GET_LIVE_URLS'
export const START_STREAM_RECORD = 'START_STREAM_RECORD'
export const STOP_STREAM_RECORD = 'STOP_STREAM_RECORD'
export const STREAM_RECORD_END = 'STREAM_RECORD_END'

export const FFMPEG_PROGRESS_INFO = 'FFMPEG_PROGRESS_INFO'

export const SHOW_NOTIFICATION = 'SHOW_NOTIFICATION'

export const RECORD_DUMMY_PROCESS = { kill: () => {} }
